### PR TITLE
fix #647 uses IP address to register or unregister to Nacos

### LINKED ISSUE #647: fescar-server 0.4. and nacos server 1.0.0RC1 ERROR~!
this is  a  error log about naming.log . when is use fescar-server 0.4. and nacos server 1.0.0RC1.
i can't start fescar-server .i ask to nacos team, he tell me  ip":"viken-acer" is not right IP address.

and viken-acer is my HostName . so  please help me  how config it :(

`01 2019-03-22 14:42:36.486 INFO [main :c.a.n.c.naming] [BEAT] [] [] adding beat: {"cluster":"default","ip":"viken-acer","metadata":{},"port":8091,"scheduled":false,"serviceName":"serverAddr","weight":1.0} to beat map.
01 2019-03-22 14:42:36.578 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] public registering service serverAddr with instance: {"clusterName":"default","enabled":true,"ip":"viken-acer","metadata":{},"port":8091,"valid":true,"weight":1.0}
01 2019-03-22 14:42:36.594 ERROR [main :c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:Fei-Wang:8091:unknown:default_1.0_true_false_default
01 2019-03-22 14:42:36.596 ERROR [main :c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(localhost
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:152)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:88)
`

### PR DESCRIPTION
**Pull request by xingfudeshi**
### Ⅰ. Describe what this PR did
when use Nacos as our discovery service,
we should always use IP address instead of Hostname to register or unregister to Nacos.otherwise,you will get the following exceptions:
`01 2019-03-29 09:42:21.164 ERROR [main :c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:CHINA-20181022Z:8091:unknown:default_1.0_true_false_default
01 2019-03-29 09:42:21.166 ERROR [main :c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(localhost
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:153)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:88)`

Perhaps Nacos only supports IP addresses to register or deregister a instance.

### Ⅱ. Does this pull request fix one issue?

#647

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
I've done integration testing with our samples.

### CODE REVIEW

File: discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java [hunk 1]
```diff
@@ -208,19 +206,19 @@ private static String getClusterName() {
...
-            + PRO_SERVER_ADDR_KEY;
+                + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
+                + PRO_SERVER_ADDR_KEY;
     }
 
     private static String getNacosNameSpaceFileKey() {
         return ConfigurationKeys.FILE_ROOT_REGISTRY + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR + REGISTRY_TYPE
-            + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
-            + PRO_NAMESPACE_KEY;
+                + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
```
Comment (slievrly) [inline discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java]: code style tab？

File: discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java [hunk 2]
```diff
@@ -121,7 +119,7 @@ public void unsubscribe(String cluster, EventListener listener) throws Exception
         }
         if (!LISTENER_SERVICE_MAP.containsKey(clusterName)) {
             List<String> clusters = new ArrayList<>();
-            clusters.add(clusterName);
+            clusters.add(getClusterName());
```
Comment (slievrly) [inline discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java]: clusterName？

**Comment by slievrly** [comment]
fix pr title

File: discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java (hunk 1 above)
Comment (xingfudeshi) [reply discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java]: resolved

File: discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java (hunk 2 above)
Comment (xingfudeshi) [reply discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java]: restored to clusterName
