### PR TITLE
fix up ,eureka client renew request is error#569

### LINKED ISSUE #569: About sending renew request to eureka server
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Method "fescar-discovery: EurekaRegistryServiceImpl-getInstanceId()"  builds the instanceId with pattern "%s/%s:%d" (appName, ipaddress, port).
Eureka client(DiscoveryClient-renew()) sends renew request to the url:  myConfigEurekServerAddress/eureka/apps/<appName>/<instanceId>

There is a "/" in instanceId, so the eureka client cannot succeed to renew.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

renew success.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others: my eurke server version is 1.6.2

### PR DESCRIPTION
**Pull request by sunrui849**
### Ⅰ. Describe what this PR did
if user / to splicing instanceId,the renew request will to ***/name/ip:port, but should to ***/(name/ip:port) ,change the instanceId to name:ip:port
add unified the key uppercase,from eureka cluster name is uppercase

### Ⅱ. Does this pull request fix one issue?

fixes #569

### CODE REVIEW

File: discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java [hunk 1]
```diff
@@ -143,7 +143,7 @@ public void onEvent(EurekaEvent event) {
             });
         }
 
-        return Lists.newArrayList(CLUSTER_ADDRESS_MAP.get(clusterName));
+        return Lists.newArrayList(CLUSTER_ADDRESS_MAP.get(clusterName.toUpperCase()));
```
Comment (github-ygy) [inline discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java]: 1.better to add  toUpperCase() for clusterName when put 
`CLUSTER_ADDRESS_MAP.put(app.getName().toUpperCase(), addressSet);`
2.i have a question ,the Application 's name can be null or empty ?
